### ISSUE TITLE
Use a more meaningful templating name other than "foo" during parsing

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/data-science-pipelines-operator#16]
When templating via manifesteval [here](https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/controllers/config/templating.go#L54) we use a templating name "foo", we should have a more meaningful name as during templating failures, this name gets printed out during logging, example: 

```txt
1.6764445919248998e+09 INFO Observed a panic in reconciler: template: foo:61:24: executing "foo" at <.VisualizationServerServiceHost>: can't evaluate field VisualizationServerServiceHost in type *controllers.DSPipelineParams {"controller": "dspipeline", "controllerGroup": "dspipelines.opendatahub.io", "controllerKind": "DSPipeline", "DSPipeline": {"name":"sample","namespace":"gfrasca-dsp-op"}, "namespace": "gfrasca-dsp-op", "name": "sample", "reconcileID": "2c034801-265f-42c1-ae37-f9663177bbfb"}
panic: template: foo:61:24: executing "foo" at <.VisualizationServerServiceHost>: can't evaluate field VisualizationServerServiceHost in type *controllers.DSPipelineParams [recovered]
panic: template: foo:61:24: executing "foo" at <.VisualizationServerServiceHost>: can't evaluate field VisualizationServerServiceHost in type *controllers.DSPipelineParams
goroutine 765 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x1651940, 0xc003f9dae0})
/usr/lib/golang/src/runtime/panic.go:838 +0x207
```

**Comment by HumairAK** [comment]
fixed in #171
